routes/web.php
<?php

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Slideshows
    Route::delete('slideshows/destroy', 'SlideshowController@massDestroy')->name('slideshows.massDestroy');
    Route::post('slideshows/media', 'SlideshowController@storeMedia')->name('slideshows.storeMedia');
    Route::post('slideshows/ckmedia', 'SlideshowController@storeCKEditorImages')->name('slideshows.storeCKEditorImages');
    Route::resource('slideshows', 'SlideshowController');

    // Sobre Escolas
    Route::delete('sobre-escolas/destroy', 'SobreEscolaController@massDestroy')->name('sobre-escolas.massDestroy');
    Route::post('sobre-escolas/media', 'SobreEscolaController@storeMedia')->name('sobre-escolas.storeMedia');
    Route::post('sobre-escolas/ckmedia', 'SobreEscolaController@storeCKEditorImages')->name('sobre-escolas.storeCKEditorImages');
    Route::resource('sobre-escolas', 'SobreEscolaController');

    // Categoria
    Route::delete('categoria/destroy', 'CategoriasController@massDestroy')->name('categoria.massDestroy');
    Route::resource('categoria', 'CategoriasController');

    // Detalhes
    Route::delete('detalhes/destroy', 'DetalhesController@massDestroy')->name('detalhes.massDestroy');
    Route::post('detalhes/media', 'DetalhesController@storeMedia')->name('detalhes.storeMedia');
    Route::post('detalhes/ckmedia', 'DetalhesController@storeCKEditorImages')->name('detalhes.storeCKEditorImages');
    Route::resource('detalhes', 'DetalhesController');

    // Blogs
    Route::delete('blogs/destroy', 'BlogController@massDestroy')->name('blogs.massDestroy');
    Route::post('blogs/media', 'BlogController@storeMedia')->name('blogs.storeMedia');
    Route::post('blogs/ckmedia', 'BlogController@storeCKEditorImages')->name('blogs.storeCKEditorImages');
    Route::resource('blogs', 'BlogController');

    // Contatos
    Route::delete('contatos/destroy', 'ContatoController@massDestroy')->name('contatos.massDestroy');
    Route::resource('contatos', 'ContatoController');

    // Parceiros
    Route::delete('parceiros/destroy', 'ParceirosController@massDestroy')->name('parceiros.massDestroy');
    Route::post('parceiros/media', 'ParceirosController@storeMedia')->name('parceiros.storeMedia');
    Route::post('parceiros/ckmedia', 'ParceirosController@storeCKEditorImages')->name('parceiros.storeCKEditorImages');
    Route::resource('parceiros', 'ParceirosController');

    // Trabalheconoscos
    Route::delete('trabalheconoscos/destroy', 'TrabalheconoscoController@massDestroy')->name('trabalheconoscos.massDestroy');
    Route::post('trabalheconoscos/media', 'TrabalheconoscoController@storeMedia')->name('trabalheconoscos.storeMedia');
    Route::post('trabalheconoscos/ckmedia', 'TrabalheconoscoController@storeCKEditorImages')->name('trabalheconoscos.storeCKEditorImages');
    Route::resource('trabalheconoscos', 'TrabalheconoscoController');
});

app/Parceiro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Parceiro extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'parceiros';

    protected $appends = [
        'parceiro',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'url',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function getParceiroAttribute()
    {
        $file = $this->getMedia('parceiro')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }
}

app/Http/Controllers/Admin/ParceirosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyParceiroRequest;
use App\Http\Requests\StoreParceiroRequest;
use App\Http\Requests\UpdateParceiroRequest;
use App\Parceiro;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class ParceirosController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('parceiro_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parceiros = Parceiro::all();

        return view('admin.parceiros.index', compact('parceiros'));
    }

    public function create()
    {
        abort_if(Gate::denies('parceiro_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.parceiros.create');
    }

    public function store(StoreParceiroRequest $request)
    {
        $parceiro = Parceiro::create($request->all());

        if ($request->input('parceiro', false)) {
            $parceiro->addMedia(storage_path('tmp/uploads/' . $request->input('parceiro')))->toMediaCollection('parceiro');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $parceiro->id]);
        }

        return redirect()->route('admin.parceiros.index');
    }

    public function edit(Parceiro $parceiro)
    {
        abort_if(Gate::denies('parceiro_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.parceiros.edit', compact('parceiro'));
    }

    public function update(UpdateParceiroRequest $request, Parceiro $parceiro)
    {
        $parceiro->update($request->all());

        if ($request->input('parceiro', false)) {
            if (!$parceiro->parceiro || $request->input('parceiro') !== $parceiro->parceiro->file_name) {
                $parceiro->addMedia(storage_path('tmp/uploads/' . $request->input('parceiro')))->toMediaCollection('parceiro');
            }
        } elseif ($parceiro->parceiro) {
            $parceiro->parceiro->delete();
        }

        return redirect()->route('admin.parceiros.index');
    }

    public function show(Parceiro $parceiro)
    {
        abort_if(Gate::denies('parceiro_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.parceiros.show', compact('parceiro'));
    }

    public function destroy(Parceiro $parceiro)
    {
        abort_if(Gate::denies('parceiro_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parceiro->delete();

        return back();
    }

    public function massDestroy(MassDestroyParceiroRequest $request)
    {
        Parceiro::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('parceiro_create') && Gate::denies('parceiro_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Parceiro();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media', 'public');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/parceiros/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.parceiro.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.parceiros.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="parceiro">{{ trans('cruds.parceiro.fields.parceiro') }}</label>
                <div class="needsclick dropzone {{ $errors->has('parceiro') ? 'is-invalid' : '' }}" id="parceiro-dropzone">
                </div>
                @if($errors->has('parceiro'))
                    <span class="text-danger">{{ $errors->first('parceiro') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.parceiro.fields.parceiro_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="url">{{ trans('cruds.parceiro.fields.url') }}</label>
                <input class="form-control {{ $errors->has('url') ? 'is-invalid' : '' }}" type="text" name="url" id="url" value="{{ old('url', '') }}">
                @if($errors->has('url'))
                    <span class="text-danger">{{ $errors->first('url') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.parceiro.fields.url_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.parceiroDropzone = {
    url: '{{ route('admin.parceiros.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="parceiro"]').remove()
      $('form').append('<input type="hidden" name="parceiro" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="parceiro"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($parceiro) && $parceiro->parceiro)
      var file = {!! json_encode($parceiro->parceiro) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $parceiro->parceiro->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="parceiro" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/parceiros/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.parceiro.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.parceiros.update", [$parceiro->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="parceiro">{{ trans('cruds.parceiro.fields.parceiro') }}</label>
                <div class="needsclick dropzone {{ $errors->has('parceiro') ? 'is-invalid' : '' }}" id="parceiro-dropzone">
                </div>
                @if($errors->has('parceiro'))
                    <span class="text-danger">{{ $errors->first('parceiro') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.parceiro.fields.parceiro_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="url">{{ trans('cruds.parceiro.fields.url') }}</label>
                <input class="form-control {{ $errors->has('url') ? 'is-invalid' : '' }}" type="text" name="url" id="url" value="{{ old('url', $parceiro->url) }}">
                @if($errors->has('url'))
                    <span class="text-danger">{{ $errors->first('url') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.parceiro.fields.url_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.parceiroDropzone = {
    url: '{{ route('admin.parceiros.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="parceiro"]').remove()
      $('form').append('<input type="hidden" name="parceiro" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="parceiro"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($parceiro) && $parceiro->parceiro)
      var file = {!! json_encode($parceiro->parceiro) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $parceiro->parceiro->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="parceiro" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/parceiros/index.blade.php
@extends('layouts.admin')
@section('content')
@can('parceiro_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.parceiros.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.parceiro.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.parceiro.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Parceiro">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.parceiro.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.parceiro.fields.parceiro') }}
                        </th>
                        <th>
                            {{ trans('cruds.parceiro.fields.url') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($parceiros as $key => $parceiro)
                        <tr data-entry-id="{{ $parceiro->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $parceiro->id ?? '' }}
                            </td>
                            <td>
                                @if($parceiro->parceiro)
                                    <a href="{{ $parceiro->parceiro->getUrl() }}" target="_blank">
                                        <img src="{{ $parceiro->parceiro->getUrl('thumb') }}" width="50px" height="50px">
                                    </a>
                                @endif
                            </td>
                            <td>
                                {{ $parceiro->url ?? '' }}
                            </td>
                            <td>
                                @can('parceiro_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.parceiros.show', $parceiro->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('parceiro_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.parceiros.edit', $parceiro->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('parceiro_delete')
                                    <form action="{{ route('admin.parceiros.destroy', $parceiro->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('parceiro_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.parceiros.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Parceiro:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/parceiros/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.parceiro.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.parceiros.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.parceiro.fields.id') }}
                        </th>
                        <td>
                            {{ $parceiro->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.parceiro.fields.parceiro') }}
                        </th>
                        <td>
                            @if($parceiro->parceiro)
                                <a href="{{ $parceiro->parceiro->getUrl() }}" target="_blank">
                                    <img src="{{ $parceiro->parceiro->getUrl('thumb') }}" width="50px" height="50px">
                                </a>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.parceiro.fields.url') }}
                        </th>
                        <td>
                            {{ $parceiro->url }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.parceiros.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection