routes/web.php
<?php

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Slideshows
    Route::delete('slideshows/destroy', 'SlideshowController@massDestroy')->name('slideshows.massDestroy');
    Route::post('slideshows/media', 'SlideshowController@storeMedia')->name('slideshows.storeMedia');
    Route::post('slideshows/ckmedia', 'SlideshowController@storeCKEditorImages')->name('slideshows.storeCKEditorImages');
    Route::resource('slideshows', 'SlideshowController');

    // Sobre Escolas
    Route::delete('sobre-escolas/destroy', 'SobreEscolaController@massDestroy')->name('sobre-escolas.massDestroy');
    Route::post('sobre-escolas/media', 'SobreEscolaController@storeMedia')->name('sobre-escolas.storeMedia');
    Route::post('sobre-escolas/ckmedia', 'SobreEscolaController@storeCKEditorImages')->name('sobre-escolas.storeCKEditorImages');
    Route::resource('sobre-escolas', 'SobreEscolaController');

    // Categoria
    Route::delete('categoria/destroy', 'CategoriasController@massDestroy')->name('categoria.massDestroy');
    Route::resource('categoria', 'CategoriasController');

    // Detalhes
    Route::delete('detalhes/destroy', 'DetalhesController@massDestroy')->name('detalhes.massDestroy');
    Route::post('detalhes/media', 'DetalhesController@storeMedia')->name('detalhes.storeMedia');
    Route::post('detalhes/ckmedia', 'DetalhesController@storeCKEditorImages')->name('detalhes.storeCKEditorImages');
    Route::resource('detalhes', 'DetalhesController');

    // Blogs
    Route::delete('blogs/destroy', 'BlogController@massDestroy')->name('blogs.massDestroy');
    Route::post('blogs/media', 'BlogController@storeMedia')->name('blogs.storeMedia');
    Route::post('blogs/ckmedia', 'BlogController@storeCKEditorImages')->name('blogs.storeCKEditorImages');
    Route::resource('blogs', 'BlogController');

    // Contatos
    Route::delete('contatos/destroy', 'ContatoController@massDestroy')->name('contatos.massDestroy');
    Route::resource('contatos', 'ContatoController');

    // Parceiros
    Route::delete('parceiros/destroy', 'ParceirosController@massDestroy')->name('parceiros.massDestroy');
    Route::post('parceiros/media', 'ParceirosController@storeMedia')->name('parceiros.storeMedia');
    Route::post('parceiros/ckmedia', 'ParceirosController@storeCKEditorImages')->name('parceiros.storeCKEditorImages');
    Route::resource('parceiros', 'ParceirosController');

    // Trabalheconoscos
    Route::delete('trabalheconoscos/destroy', 'TrabalheconoscoController@massDestroy')->name('trabalheconoscos.massDestroy');
    Route::post('trabalheconoscos/media', 'TrabalheconoscoController@storeMedia')->name('trabalheconoscos.storeMedia');
    Route::post('trabalheconoscos/ckmedia', 'TrabalheconoscoController@storeCKEditorImages')->name('trabalheconoscos.storeCKEditorImages');
    Route::resource('trabalheconoscos', 'TrabalheconoscoController');
});

app/Slideshow.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Slideshow extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'slideshows';

    protected $appends = [
        'imagem',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function getImagemAttribute()
    {
        $file = $this->getMedia('imagem')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }
}

app/Http/Controllers/Admin/SlideshowController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroySlideshowRequest;
use App\Http\Requests\StoreSlideshowRequest;
use App\Http\Requests\UpdateSlideshowRequest;
use App\Slideshow;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SlideshowController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('slideshow_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $slideshows = Slideshow::all();

        return view('admin.slideshows.index', compact('slideshows'));
    }

    public function create()
    {
        abort_if(Gate::denies('slideshow_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.slideshows.create');
    }

    public function store(StoreSlideshowRequest $request)
    {
        $slideshow = Slideshow::create($request->all());

        if ($request->input('imagem', false)) {
            $slideshow->addMedia(storage_path('tmp/uploads/' . $request->input('imagem')))->toMediaCollection('imagem');
        }

        return redirect()->route('admin.slideshows.index');
    }

    public function edit(Slideshow $slideshow)
    {
        abort_if(Gate::denies('slideshow_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.slideshows.edit', compact('slideshow'));
    }

    public function update(UpdateSlideshowRequest $request, Slideshow $slideshow)
    {
        $slideshow->update($request->all());

        if ($request->input('imagem', false)) {
            if (!$slideshow->imagem || $request->input('imagem') !== $slideshow->imagem->file_name) {
                $slideshow->addMedia(storage_path('tmp/uploads/' . $request->input('imagem')))->toMediaCollection('imagem');
            }
        } elseif ($slideshow->imagem) {
            $slideshow->imagem->delete();
        }

        return redirect()->route('admin.slideshows.index');
    }

    public function show(Slideshow $slideshow)
    {
        abort_if(Gate::denies('slideshow_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.slideshows.show', compact('slideshow'));
    }

    public function destroy(Slideshow $slideshow)
    {
        abort_if(Gate::denies('slideshow_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $slideshow->delete();

        return back();
    }

    public function massDestroy(MassDestroySlideshowRequest $request)
    {
        Slideshow::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/slideshows/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.slideshow.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.slideshows.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="imagem">{{ trans('cruds.slideshow.fields.imagem') }}</label>
                <div class="needsclick dropzone {{ $errors->has('imagem') ? 'is-invalid' : '' }}" id="imagem-dropzone">
                </div>
                @if($errors->has('imagem'))
                    <span class="text-danger">{{ $errors->first('imagem') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.slideshow.fields.imagem_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.imagemDropzone = {
    url: '{{ route('admin.slideshows.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="imagem"]').remove()
      $('form').append('<input type="hidden" name="imagem" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="imagem"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($slideshow) && $slideshow->imagem)
      var file = {!! json_encode($slideshow->imagem) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $slideshow->imagem->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="imagem" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/slideshows/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.slideshow.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.slideshows.update", [$slideshow->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="imagem">{{ trans('cruds.slideshow.fields.imagem') }}</label>
                <div class="needsclick dropzone {{ $errors->has('imagem') ? 'is-invalid' : '' }}" id="imagem-dropzone">
                </div>
                @if($errors->has('imagem'))
                    <span class="text-danger">{{ $errors->first('imagem') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.slideshow.fields.imagem_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.imagemDropzone = {
    url: '{{ route('admin.slideshows.storeMedia') }}',
    maxFilesize: 2, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 2,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="imagem"]').remove()
      $('form').append('<input type="hidden" name="imagem" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="imagem"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($slideshow) && $slideshow->imagem)
      var file = {!! json_encode($slideshow->imagem) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $slideshow->imagem->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="imagem" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/slideshows/index.blade.php
@extends('layouts.admin')
@section('content')
@can('slideshow_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.slideshows.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.slideshow.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.slideshow.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Slideshow">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.slideshow.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.slideshow.fields.imagem') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($slideshows as $key => $slideshow)
                        <tr data-entry-id="{{ $slideshow->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $slideshow->id ?? '' }}
                            </td>
                            <td>
                                @if($slideshow->imagem)
                                    <a href="{{ $slideshow->imagem->getUrl() }}" target="_blank">
                                        <img src="{{ $slideshow->imagem->getUrl('thumb') }}" width="50px" height="50px">
                                    </a>
                                @endif
                            </td>
                            <td>
                                @can('slideshow_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.slideshows.show', $slideshow->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('slideshow_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.slideshows.edit', $slideshow->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('slideshow_delete')
                                    <form action="{{ route('admin.slideshows.destroy', $slideshow->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('slideshow_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.slideshows.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Slideshow:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/slideshows/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.slideshow.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.slideshows.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.slideshow.fields.id') }}
                        </th>
                        <td>
                            {{ $slideshow->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.slideshow.fields.imagem') }}
                        </th>
                        <td>
                            @if($slideshow->imagem)
                                <a href="{{ $slideshow->imagem->getUrl() }}" target="_blank">
                                    <img src="{{ $slideshow->imagem->getUrl('thumb') }}" width="50px" height="50px">
                                </a>
                            @endif
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.slideshows.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection