routes/web.php
<?php

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Slideshows
    Route::delete('slideshows/destroy', 'SlideshowController@massDestroy')->name('slideshows.massDestroy');
    Route::post('slideshows/media', 'SlideshowController@storeMedia')->name('slideshows.storeMedia');
    Route::post('slideshows/ckmedia', 'SlideshowController@storeCKEditorImages')->name('slideshows.storeCKEditorImages');
    Route::resource('slideshows', 'SlideshowController');

    // Sobre Escolas
    Route::delete('sobre-escolas/destroy', 'SobreEscolaController@massDestroy')->name('sobre-escolas.massDestroy');
    Route::post('sobre-escolas/media', 'SobreEscolaController@storeMedia')->name('sobre-escolas.storeMedia');
    Route::post('sobre-escolas/ckmedia', 'SobreEscolaController@storeCKEditorImages')->name('sobre-escolas.storeCKEditorImages');
    Route::resource('sobre-escolas', 'SobreEscolaController');

    // Categoria
    Route::delete('categoria/destroy', 'CategoriasController@massDestroy')->name('categoria.massDestroy');
    Route::resource('categoria', 'CategoriasController');

    // Detalhes
    Route::delete('detalhes/destroy', 'DetalhesController@massDestroy')->name('detalhes.massDestroy');
    Route::post('detalhes/media', 'DetalhesController@storeMedia')->name('detalhes.storeMedia');
    Route::post('detalhes/ckmedia', 'DetalhesController@storeCKEditorImages')->name('detalhes.storeCKEditorImages');
    Route::resource('detalhes', 'DetalhesController');

    // Blogs
    Route::delete('blogs/destroy', 'BlogController@massDestroy')->name('blogs.massDestroy');
    Route::post('blogs/media', 'BlogController@storeMedia')->name('blogs.storeMedia');
    Route::post('blogs/ckmedia', 'BlogController@storeCKEditorImages')->name('blogs.storeCKEditorImages');
    Route::resource('blogs', 'BlogController');

    // Contatos
    Route::delete('contatos/destroy', 'ContatoController@massDestroy')->name('contatos.massDestroy');
    Route::resource('contatos', 'ContatoController');

    // Parceiros
    Route::delete('parceiros/destroy', 'ParceirosController@massDestroy')->name('parceiros.massDestroy');
    Route::post('parceiros/media', 'ParceirosController@storeMedia')->name('parceiros.storeMedia');
    Route::post('parceiros/ckmedia', 'ParceirosController@storeCKEditorImages')->name('parceiros.storeCKEditorImages');
    Route::resource('parceiros', 'ParceirosController');

    // Trabalheconoscos
    Route::delete('trabalheconoscos/destroy', 'TrabalheconoscoController@massDestroy')->name('trabalheconoscos.massDestroy');
    Route::post('trabalheconoscos/media', 'TrabalheconoscoController@storeMedia')->name('trabalheconoscos.storeMedia');
    Route::post('trabalheconoscos/ckmedia', 'TrabalheconoscoController@storeCKEditorImages')->name('trabalheconoscos.storeCKEditorImages');
    Route::resource('trabalheconoscos', 'TrabalheconoscoController');
});

app/Http/Controllers/Admin/CategoriasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Categorium;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCategoriumRequest;
use App\Http\Requests\StoreCategoriumRequest;
use App\Http\Requests\UpdateCategoriumRequest;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CategoriasController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('categorium_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categoria = Categorium::all();

        return view('admin.categoria.index', compact('categoria'));
    }

    public function create()
    {
        abort_if(Gate::denies('categorium_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.categoria.create');
    }

    public function store(StoreCategoriumRequest $request)
    {
        $categorium = Categorium::create($request->all());

        return redirect()->route('admin.categoria.index');
    }

    public function edit(Categorium $categorium)
    {
        abort_if(Gate::denies('categorium_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.categoria.edit', compact('categorium'));
    }

    public function update(UpdateCategoriumRequest $request, Categorium $categorium)
    {
        $categorium->update($request->all());

        return redirect()->route('admin.categoria.index');
    }

    public function show(Categorium $categorium)
    {
        abort_if(Gate::denies('categorium_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categorium->load('categoriaDetalhes');

        return view('admin.categoria.show', compact('categorium'));
    }

    public function destroy(Categorium $categorium)
    {
        abort_if(Gate::denies('categorium_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categorium->delete();

        return back();
    }

    public function massDestroy(MassDestroyCategoriumRequest $request)
    {
        Categorium::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/categoria/relationships/categoriaDetalhes.blade.php
<div class="m-3">
    @can('detalhe_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.detalhes.create") }}">
                    {{ trans('global.add') }} {{ trans('cruds.detalhe.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.detalhe.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-Detalhe">
                    <thead>
                        <tr>
                            <th width="10">

                            </th>
                            <th>
                                {{ trans('cruds.detalhe.fields.id') }}
                            </th>
                            <th>
                                {{ trans('cruds.detalhe.fields.categoria') }}
                            </th>
                            <th>
                                {{ trans('cruds.detalhe.fields.imagem') }}
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($detalhes as $key => $detalhe)
                            <tr data-entry-id="{{ $detalhe->id }}">
                                <td>

                                </td>
                                <td>
                                    {{ $detalhe->id ?? '' }}
                                </td>
                                <td>
                                    {{ $detalhe->categoria->nome ?? '' }}
                                </td>
                                <td>
                                    @if($detalhe->imagem)
                                        <a href="{{ $detalhe->imagem->getUrl() }}" target="_blank">
                                            <img src="{{ $detalhe->imagem->getUrl('thumb') }}" width="50px" height="50px">
                                        </a>
                                    @endif
                                </td>
                                <td>
                                    @can('detalhe_show')
                                        <a class="btn btn-xs btn-primary" href="{{ route('admin.detalhes.show', $detalhe->id) }}">
                                            {{ trans('global.view') }}
                                        </a>
                                    @endcan

                                    @can('detalhe_edit')
                                        <a class="btn btn-xs btn-info" href="{{ route('admin.detalhes.edit', $detalhe->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endcan

                                    @can('detalhe_delete')
                                        <form action="{{ route('admin.detalhes.destroy', $detalhe->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                        </form>
                                    @endcan

                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('detalhe_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.detalhes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Detalhe:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection